### ISSUE TITLE
Release v1.2.0-M9

### ISSUE THREAD

**Issue by juanpedromoreno** [alexarchambault/argonaut-shapeless#116]
Is there any chance to get a new release including https://github.com/alexarchambault/argonaut-shapeless/pull/110?

It would be really appreciated.

**Comment by alexarchambault** [comment]
Done, [`1.2.0-M9`](https://github.com/alexarchambault/argonaut-shapeless/releases/tag/v1.2.0-M9) is out.

**Comment by juanpedromoreno** [comment]
Thank you!
