### ISSUE TITLE
Support missing fields if they can represent empty containers

### ISSUE THREAD

**Issue by eirirlar** [alexarchambault/argonaut-shapeless#52]
I have two cases that myself and some others have use for in several projects. Best to illustrate with an example:
1)

```
case class Person (id:Option[Long], name:String)
import argonaut._,Argonaut._,Shapeless._
val dec = """{"id":null,"name":"My Name"}""".decode[Person]

```
That _id:null_ in the json to be parsed is very annoying. Some frameworks, like Ember, don't produce it by default. Unfortunately the following doesn't work:

`val dec = """{"name":"My Name"}""".decode[Person]
`

2)
Let's take another example:
case class Person (name:String, adressRefs:List[Long])
import argonaut._,Argonaut._,Shapeless._
val dec = """{"name":"My Name","addressRefs":[]}""".decode[Person]

That _addressRefs:[]_ in the json to be parsed seems uneccessary; it's an empty list, should be possible to understand that the user means the same when parsing this json:

`val dec = """{"name":"My Name"}""".decode[Person]
`

Regarding 1), this is functionality you get "for free" when using argonaut.CodecJson.derive[Person].

Regarding 2), I didn't find any support for it in Argonaut and ended up wrapping lists in options, which feels wrong in most cases.

Otherwise thanks for a great library!

**Comment by alexarchambault** [comment]
@eirirlar What version of argonaut-shapeless are you using?

Using argonaut-shapeless `1.0.0-M1`, `val dec = """{"name":"My Name"}""".decode[Person]` works for me.

Also, if you don't want the `null` to appear in the output JSON, you can either tweak the pretty-printing of argonaut, like
```scala
@ argonaut.PrettyParams.spaces2.copy(dropNullKeys = true).pretty(
    Person(None, "My Name").asJson
  )
res3: String = """
{
  "name" : "My Name"
}
"""
```
or use default values, like
```scala
case class Person(id: Option[Long] = None, name: String)
```
(default values aren't put in the output JSON).

**Comment by alexarchambault** [comment]
Default values also allow to address 2) :-), like
```scala
case class Person(name: String, adressRefs: List[Long] = Nil)
```
which allows to decoding be fine with no `addressRefs` in the output, and won't print it if it's empty, as the empty list is the default value.

**Comment by eirirlar** [comment]
I use the following maven dependency:
        <dependency>
            <groupId>com.github.alexarchambault</groupId>
            <artifactId>argonaut-shapeless_2.11</artifactId>
            <version>6.1</version>
        </dependency>

**Comment by alexarchambault** [comment]
That's an old one :-) You should use the one advertised in the README, that is `"com.github.alexarchambault" %% "argonaut-shapeless_6.1" % "1.0.0-M1"`.

**Comment by eirirlar** [comment]
Alright, trying that now :)

**Comment by eirirlar** [comment]
That worked! Awesome, thanks :)

**Comment by flyrev** [comment]
So, for Maven users, it will be 
http://mvnrepository.com/artifact/com.github.alexarchambault/argonaut-shapeless_6.1_2.11
and not
http://mvnrepository.com/artifact/com.github.alexarchambault/argonaut-shapeless_2.11/6.1
