### ISSUE TITLE
Missing interpolator issue in `1.1.0-RC1`

### ISSUE THREAD

**Issue by AlecZorab** [alexarchambault/argonaut-shapeless#60]
when compiling my project using `1.1.0-RC1`, but not `1.0.0-RC1` or `1.0.0-M1` I see the following:

```
> reload
[info] Loading global plugins from C:\Users\azorab\.sbt\0.13\plugins
[info] Loading project definition from C:\dev\prj\art\project
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[info] Set current project to core (in build file:/C:/dev/prj/art/)
> clean
[success] Total time: 1 s, completed 01-Mar-2016 17:48:11
> package
[info] Updating {file:/C:/dev/prj/art/}core...
[info] Resolving jline#jline;2.12.1 ...
[info] Writing build properties to: C:\dev\prj\art\core\src\main\managed\art-core\build.properties
[info] Done updating.
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn]  * com.chuusai:shapeless_2.11:2.0.0 -> 2.3.0
[warn]  * org.spire-math:spire_2.11:0.7.4 -> 0.11.0
[warn] Run 'evicted' to see detailed eviction warnings
[info] Compiling 79 Scala sources to C:\dev\prj\art\core\target\scala-2.11\classes...
[error] possible missing interpolator: detected an interpolated expression
[error] one error found
[error] (core/compile:compileIncremental) Compilation failed
[error] Total time: 8 s, completed 01-Mar-2016 17:48:20
```

Note that the position seems to have disappeared.

the warning (which I treat as an error) is generated here: https://github.com/scala/scala/blob/1421e3c66c7bc50c54759e48a7492923e391d186/src/compiler/scala/tools/nsc/typechecker/Typers.scala#L5218

**Comment by som-snytt** [comment]
This suffices to trigger the warning:

https://github.com/milessabin/shapeless/blob/master/core/src/main/scala/shapeless/lazy.scala#L228

**Comment by alexarchambault** [comment]
@som-snytt Exactly, I just stumbled upon it too.

**Comment by alexarchambault** [comment]
@AlecZorab Can you try to compile your codebase with a patched version of shapeless, dropping the `$` signs in the quasi-quote? To know if that's the origin of the problem.

**Comment by AlecZorab** [comment]
will do!

**Comment by AlecZorab** [comment]
@milessabin is already attacking upstream and I'm pretty sure that he's going to get a fix published (whilst on a flight) faster than I'm going to get a patched version built on my machine!

**Comment by AlecZorab** [comment]
confirmed that dropping the `$$` stops the warning.

Closing, apologies for the noise :D

**Comment by alexarchambault** [comment]
@AlecZorab np, it's not noise, it means I'll have to do a release with shapeless 2.3.1!
