### ISSUE TITLE
Failed compilation on 1.1.0-RC1 and not on 1.0.0-RC1

### ISSUE THREAD

**Issue by coltfred** [alexarchambault/argonaut-shapeless#61]
```
sealed trait Source extends Serializable

case object Source1 extends Source
case object Source2 extends Source

object Source {
  val codec = EncodeJson.of[Source]
}
```

The error is the following:

```
[error] possible missing interpolator: detected an interpolated expression
[error] one error found
[error] (compile:compileIncremental) Compilation failed
```

The following fails to compile with the version that depends on shapeless 2.3.0, but not on 2.2.5. Let me know if I can be of further assistance.

**Comment by alexarchambault** [comment]
@coltfred That's the same issue as https://github.com/alexarchambault/argonaut-shapeless/issues/60. That should be fixed in shapeless 2.3.1.

**Comment by coltfred** [comment]
@alexarchambault - @milessabin published 2.3.1-RC1, have you tried to build with it?

**Comment by alexarchambault** [comment]
Yeah, I can confirm 2.3.1-RC1 fixes this. I'll do a release as soon as 2.3.1 is out.

**Comment by milessabin** [comment]
I'll release 2.3.1 tomorrow if there are no show stoppers.

**Comment by coltfred** [comment]
On 2.3.2 so closing
