### ISSUE TITLE
add a trait for ArgonautShapeless

### ISSUE THREAD

**Issue by leclark** [alexarchambault/argonaut-shapeless#89]
Argonaut defines a trait and an object that makes it a little more flexible to use than the ArgonautShapeless setup.

e.g. 
```
object Argonaut extends Argonauts

trait Argonauts extends
 ...
```  

would the team be open to adding something like this?
```
object ArgonautShapeless extends ArgonautShapeless

trait ArgonautShapeless
  extends SingletonInstances
  with DerivedInstances {

  object Cached
    extends SingletonInstances
    with CachedDerivedInstances
}
```

I can put up a PR if that helps.

**Comment by alexarchambault** [comment]
The team would be ok (with the team = me 😛).

**Comment by leclark** [comment]
Haha 
I put a PR for the change, thanks for being so responsive.
